spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 20000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小
  rule:
    #远程规则
    remote:
      - name: ad-pc
        path: https://cdn.jsdelivr.net/gh/o0HalfLife0o/list@master/ad-pc.txt

      - name: ad-mo
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-mo.txt

      - name: ad2
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad2.txt

      - name: ad3
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad3.txt

      - name: ad-edentw
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-edentw.txt

      - name: hosts
        path: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

      - name: rule.txt
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt

      - name: easylistchina+easylist.txt
        path: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

      - name: Easylist-China.txt
        path: https://raw.githubusercontent.com/Hackl0us/AdBlock-Rules-Mirror/master/Easylist-China.txt
        
      - name: easylistchina.txt
        path: https://easylist-downloads.adblockplus.org/easylistchina.txt

      - name: adblock-for-dnsmasq.conf
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf

      - name: easylist.txt
        path: https://anti-ad.net/easylist.txt

      - name:KADhosts.txt
        path: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt

      - name: hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts

      - name: w3kbl.txt
        path: https://v.firebog.net/hosts/static/w3kbl.txt

      - name: spammers.txt
        path: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
        
      - name: hosts
        path: https://someonewhocares.org/hosts/zero/hosts
		
      - name: hosts
        path: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
		
      - name: hosts.txt
        path: https://winhelp2002.mvps.org/hosts.txt
		
      - name: neohostsbasic.txt
        path: https://v.firebog.net/hosts/neohostsbasic.txt
		
      - name: SNAFU.txt
        path: https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
		
      - name: hosts-file.txt
        path: https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
		
      - name: AdguardDNS.txt
        path: https://v.firebog.net/hosts/AdguardDNS.txt
		
      - name: Admiral.txt
        path: https://v.firebog.net/hosts/Admiral.txt
		
      - name: adservers.txt
        path: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
		
      - name: simple_ad.txt
        path: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
		
      - name: Easylist.txt
        path: https://v.firebog.net/hosts/Easylist.txt
		
      - name: plaintext
        path: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
		
      - name: hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
		
      - name: hosts
        path: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
		
      - name: hosts
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
		
      - name: Easyprivacy.txt
        path: https://v.firebog.net/hosts/Easyprivacy.txt
		
      - name: Prigent-Ads.txt
        path: https://v.firebog.net/hosts/Prigent-Ads.txt
		
      - name: hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
		
      - name: spy.txt
        path: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
		
      - name: firstparty-trackers-hosts.txt
        path: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
		
      - name: ads-and-tracking-extended.txt
        path: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
		
      - name: android-tracking.txt
        path: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
		
      - name: SmartTV.txt
        path: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
		
      - name: AmazonFireTV.txt
        path: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
		
      - name: notrack-blocklist.txt
        path: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
		
      - name: AntiMalwareHosts.txt
        path: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
		
      - name: latestdomains.txt
        path: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
		
      - name: simple_malvertising.txt
        path: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
		
      - name: Prigent-Crypto.txt
        path: https://v.firebog.net/hosts/Prigent-Crypto.txt
		
      - name: add.Risk/hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
		
      - name: bad_lists/Mandiant_APT1_Report_Appendix_D.txt
        path: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
		
      - name: phishing_army_blocklist_extended.txt
        path: https://phishing.army/download/phishing_army_blocklist_extended.txt
		
      - name: phishing-filter-hosts.txt
        path: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
		
      - name: notrack-malware.txt
        path: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
		
      - name: RPiList-Malware.txt
        path: https://v.firebog.net/hosts/RPiList-Malware.txt
		
      - name: RPiList-Phishing.txt
        path: https://v.firebog.net/hosts/RPiList-Phishing.txt
		
      - name: main-blacklist.txt
        path: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
		
      - name: hosts
        path: https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
		
      - name: hostfile
        path: https://urlhaus.abuse.ch/downloads/hostfile
		
      - name: Prigent-Malware.txt
        path: https://v.firebog.net/hosts/Prigent-Malware.txt
		
      - name: hosts_browser
        path: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
		
      - name: pi_blocklist_porn_top1m.list
        path: https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list
		
      - name: Prigent-Adult.txt
        path: https://v.firebog.net/hosts/Prigent-Adult.txt
		
      - name: facebook.txt
        path: https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
		
      - name: easyprivacy.txt
        path: https://easylist-downloads.adblockplus.org/easyprivacy.txt
		
      - name: cjx-annoyance.txt
        path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
		
      - name: abp
        path: https://www.i-dont-care-about-cookies.eu/abp
		
      - name: zhihu-strict.txt
        path: https://raw.githubusercontent.com/zsakvo/AdGuard-Custom-Rule/master/rule/zhihu-strict.txt
		
      - name: kill-baidu-ad.txt
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/kill-baidu-ad.txt
		
      - name: ADgk.txt
        path: https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt
		
      - name: video.txt
        path: https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/video.txt
		
      - name: lazy.txt
        path: https://raw.githubusercontent.com/adbyby/xwhyc-rules/master/lazy.txt
		
      - name: anti-ad-easylist.txt
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
		
      - name: all.txt
        path: https://raw.githubusercontent.com/BlueSkyXN/AdGuardHomeRules/master/all.txt
		
      - name: anti-ad-easylist.txt
        path: https://cdn.jsdelivr.net/gh/privacy-protection-tools/anti-AD@master/anti-ad-easylist.txt
		
      - name: easylist.txt
        path: https://easylist-downloads.adblockplus.org/easylist.txt
		
      - name: GoodbyeAds-Ultra.txt
        path: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds-Ultra.txt
		
      - name: plaintext
        path: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
		
      - name: fanboy-social.txt
        path: https://easylist.to/easylist/fanboy-social.txt
		
      - name: fanboy-annoyance.txt
        path: https://easylist.to/easylist/fanboy-annoyance.txt
		
      - name: fanboy-cookiemonster.txt
        path: https://secure.fanboy.co.nz/fanboy-cookiemonster.txt
		
      - name: fanboy-antifacebook.txt
        path: https://fanboy.co.nz/fanboy-antifacebook.txt
		
      - name: 14.txt
        path: https://filters.adtidy.org/extension/ublock/filters/14.txt
		
      - name: enhancedstats.txt
        path: https://www.fanboy.co.nz/enhancedstats.txt
		
      - name: 3.txt
        path: https://filters.adtidy.org/extension/ublock/filters/3.txt
		
      - name: easylist.txt
        path: https://easylist.to/easylist/easylist.txt
		
      - name: 11.txt
        path: https://filters.adtidy.org/extension/ublock/filters/11.txt
		
      - name: 2_without_easylist.txt
        path: https://filters.adtidy.org/extension/ublock/filters/2_without_easylist.txt
		
      - name: antiadblockfilters.txt
        path: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt
		
      - name: fanboy-problematic-sites.txt
        path: https://fanboy.co.nz/fanboy-problematic-sites.txt
		
      - name: hosts.txt
        path: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt
		
      - name: w.txt
        path: https://raw.githubusercontent.com/DoingDog/XXKiller/main/w.txt
		
      - name: GoodbyeAds-YouTube-AdBlock-Filter.txt
        path: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt
		
      - name: GoodbyeAds-AdBlock-Filter.txt
        path: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt
		
      - name: ADH
        path: https://raw.githubusercontent.com/peizhennan/-/main/ADH
		
      - name: hosts-yt-ads
        path: https://gist.githubusercontent.com/Ewpratten/a25ae63a7200c02c850fede2f32453cf/raw/b9318009399b99e822515d388b8458557d828c37/hosts-yt-ads
		
      - name: all.txt
        path: https://raw.githubusercontent.com/xndeye/adblock_list/main/rule/all.txt
		
      - name: DD-AD.txt
        path: https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - name: 'xndeye private List'
        path: 'private.txt'

  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [xndeye Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/xndeye/adblock_list
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
