spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小
  rule:
    #远程规则
    remote:
      - name: ad-pc
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-pc.txt

      - name: ad-mo
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-mo.txt

      - name: ad2
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad2.txt

      - name: ad3
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad3.txt

      - name: ad-edentw
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-edentw.txt

      - name: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
        path: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

      - name: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt

      - name: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
        path: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

      - name: https://raw.githubusercontent.com/Hackl0us/AdBlock-Rules-Mirror/master/Easylist-China.txt
        path: https://raw.githubusercontent.com/Hackl0us/AdBlock-Rules-Mirror/master/Easylist-China.txt

      - name: https://easylist-downloads.adblockplus.org/easylistchina.txt
        path: https://easylist-downloads.adblockplus.org/easylistchina.txt

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt

      - name: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf

      - name: https://anti-ad.net/easylist.txt
        path: https://anti-ad.net/easylist.txt

      - name: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
        path: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt

      - name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts

      - name: https://v.firebog.net/hosts/static/w3kbl.txt
        path: https://v.firebog.net/hosts/static/w3kbl.txt
        
      - name: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
        path: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt

      - name: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
        path: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt

      - name: https://someonewhocares.org/hosts/zero/hosts
        path: https://someonewhocares.org/hosts/zero/hosts

      - name: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
        path: https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts

      - name: https://winhelp2002.mvps.org/hosts.txt
        path: https://winhelp2002.mvps.org/hosts.txt

      - name: https://v.firebog.net/hosts/neohostsbasic.txt
        path: https://v.firebog.net/hosts/neohostsbasic.txt

      - name: https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
        path: https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt

      - name: https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt
        path: https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt

      - name: https://v.firebog.net/hosts/AdguardDNS.txt
        path: https://v.firebog.net/hosts/AdguardDNS.txt

      - name: https://v.firebog.net/hosts/Admiral.txt
        path: https://v.firebog.net/hosts/Admiral.txt

      - name: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
        path: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt

      - name: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
        path: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt

      - name: https://v.firebog.net/hosts/Easylist.txt
        path: https://v.firebog.net/hosts/Easylist.txt

      - name: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
        path: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext

      - name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts

      - name: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
        path: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

      - name: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
        path: https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts

      - name: https://v.firebog.net/hosts/Easyprivacy.txt
        path: https://v.firebog.net/hosts/Easyprivacy.txt

      - name: https://v.firebog.net/hosts/Prigent-Ads.txt
        path: https://v.firebog.net/hosts/Prigent-Ads.txt

      - name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts

      - name: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
        path: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

      - name: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
        path: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

      - name: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
        path: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

      - name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
        path: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt

      - name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
        path: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt

      - name: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
        path: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt

      - name: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
        path: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt

      - name: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
        path: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt

      - name: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
        path: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt

      - name: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
        path: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

      - name: https://v.firebog.net/hosts/Prigent-Crypto.txt
        path: https://v.firebog.net/hosts/Prigent-Crypto.txt

      - name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts

      - name: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
        path: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt

      - name: https://phishing.army/download/phishing_army_blocklist_extended.txt
        path: https://phishing.army/download/phishing_army_blocklist_extended.txt

      - name: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
        path: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt

      - name: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
        path: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt

      - name: https://v.firebog.net/hosts/RPiList-Malware.txt
        path: https://v.firebog.net/hosts/RPiList-Malware.txt

      - name: https://v.firebog.net/hosts/RPiList-Phishing.txt
        path: https://v.firebog.net/hosts/RPiList-Phishing.txt
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - name: 'xndeye private List'
        path: 'private.txt'

  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [xndeye Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/xndeye/adblock_list
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:
        - HOSTS
        - REGEX
        - DOMAIN
        - MODIFY
