spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小
  rule:
    #远程规则
    remote:
      - name: ad-pc
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-pc.txt

      - name: ad-mo
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-mo.txt

      - name: ad2
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad2.txt

      - name: ad3
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad3.txt

      - name: ad-edentw
        path: https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-edentw.txt

      - name: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts
        path: https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

      - name: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt

      - name: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
        path: https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt

      - name: https://raw.githubusercontent.com/Hackl0us/AdBlock-Rules-Mirror/master/Easylist-China.txt
        path: https://raw.githubusercontent.com/Hackl0us/AdBlock-Rules-Mirror/master/Easylist-China.txt

      - name: https://easylist-downloads.adblockplus.org/easylistchina.txt
        path: https://easylist-downloads.adblockplus.org/easylistchina.txt

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt

      - name: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf
        path: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/adblock-for-dnsmasq.conf

      - name: https://anti-ad.net/easylist.txt
        path: https://anti-ad.net/easylist.txt

      - name: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
        path: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt

      - name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
        path: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts

      - name: https://v.firebog.net/hosts/static/w3kbl.txt
        path: https://v.firebog.net/hosts/static/w3kbl.txt
        
      - name: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
        path: https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - name: 'xndeye private List'
        path: 'private.txt'

  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [xndeye Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/xndeye/adblock_list
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
